### ISSUE TITLE
Brakuje polskich znaków używanym foncie

### ISSUE THREAD

**Issue by cudfather** [procek69/pjatk-the-burning-tomaszew#5]
Polskie znaki chyba w Times New Roman, twojej ulubionej, Łukasz.

**Comment by procek69** [comment]
tomaszew95 ma mieć nawet DOS'owy charakter

pokaż mi polskie znaki w anscii

**Comment by cudfather** [comment]
No to zamiast polskich daj odpowiedniki z ASCII. Ć -> C w Ćwiczenia itp.
