### ISSUE TITLE
Płacenie kodem nie zmniejsza "stanu konta"

### ISSUE THREAD

**Issue by cudfather** [procek69/pjatk-the-burning-tomaszew#6]
Wszystkie opcje do obdlokowania za pomocą płacenia kodem nie wymagają tej ilości kodu (np. mogę kupić coś za 1000 nie mając 1000) i nie obniżają stanu konta punktów.

**Comment by procek69** [comment]
naprawione w https://github.com/procek69/pjatk-the-burning-tomaszew/commit/a927ec29871c440e9b95faa62ff9b006cce40893
